"""Contract test: every plugin in the sibling calvin-plugins repo must produce a
valid PluginDefinition via its register_plugin_types() hook.

This catches plugin breakage in host CI before the plugin reaches a user's Pi
(where validation failures show up as failed installs and missing dashboard
regions).

The test discovers calvin-plugins via:
  1. CALVIN_PLUGINS_DIR environment variable, if set
  2. <repo_root>/../calvin-plugins (the conventional sibling layout)

If neither resolves, the test is skipped — checkouts that don't include the
plugins repo (e.g. minimal CI shards) are fine.
"""

from __future__ import annotations

import importlib.util
import os
import sys
from pathlib import Path

import pytest

from app.plugins.definitions import PluginDefinition


def _find_calvin_plugins_dir() -> Path | None:
    env = os.environ.get("CALVIN_PLUGINS_DIR")
    if env:
        candidate = Path(env).expanduser().resolve()
        return candidate if candidate.is_dir() else None
    # backend/tests/integration/this_file.py -> backend -> repo root -> ../calvin-plugins
    repo_root = Path(__file__).resolve().parents[3]
    candidate = (repo_root.parent / "calvin-plugins").resolve()
    return candidate if candidate.is_dir() else None


PLUGINS_DIR = _find_calvin_plugins_dir()


def _discover_plugin_modules() -> list[tuple[str, Path]]:
    """Return (plugin_id, plugin_py_path) pairs for every plugin in the repo."""
    if PLUGINS_DIR is None:
        return []
    found: list[tuple[str, Path]] = []
    for plugin_py in sorted(PLUGINS_DIR.glob("*/plugin.py")):
        plugin_id = plugin_py.parent.name
        found.append((plugin_id, plugin_py))
    return found


PLUGIN_MODULES = _discover_plugin_modules()

# Plugins known to fail until the scaffold script is updated to emit
# display_schema.kind instead of the legacy display_schema.type. Re-generating
# these from the fixed scaffold removes them from this list.
KNOWN_LEGACY_SCAFFOLDS = {"test-plugin", "test-plugin-frontend"}


@pytest.mark.integration
@pytest.mark.skipif(
    PLUGINS_DIR is None,
    reason="calvin-plugins sibling repo not found; set CALVIN_PLUGINS_DIR to enable",
)
@pytest.mark.skipif(
    not PLUGIN_MODULES,
    reason="calvin-plugins repo present but contains no plugins",
)
@pytest.mark.parametrize(
    "plugin_id,plugin_py",
    PLUGIN_MODULES,
    ids=[pid for pid, _ in PLUGIN_MODULES],
)
def test_plugin_definition_loads(
    plugin_id: str, plugin_py: Path, request: pytest.FixtureRequest
) -> None:
    """Loading the plugin module + normalizing its metadata must not raise."""
    if plugin_id in KNOWN_LEGACY_SCAFFOLDS:
        request.applymarker(
            pytest.mark.xfail(
                reason=(
                    "Generated by the legacy scaffold; uses display_schema.type "
                    "instead of display_schema.kind. Re-scaffold to clear."
                ),
                strict=True,
            )
        )
    module_name = f"_calvin_plugins_contract_test.{plugin_id}"
    spec = importlib.util.spec_from_file_location(module_name, plugin_py)
    assert spec is not None and spec.loader is not None, f"could not load {plugin_py}"
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    try:
        spec.loader.exec_module(module)
    except Exception as exc:  # noqa: BLE001 - we want to surface any import failure
        pytest.fail(f"{plugin_id}: failed to import plugin.py: {exc!r}")

    register = getattr(module, "register_plugin_types", None)
    assert callable(register), f"{plugin_id}: plugin.py must define register_plugin_types()"

    raw_definitions = register()
    assert isinstance(raw_definitions, list) and raw_definitions, (
        f"{plugin_id}: register_plugin_types() must return a non-empty list"
    )

    for raw in raw_definitions:
        try:
            PluginDefinition.from_raw(raw)
        except Exception as exc:  # noqa: BLE001 - any normalization failure is the bug
            pytest.fail(f"{plugin_id}: PluginDefinition.from_raw failed: {exc!r}")
