"""Initial migration from models

Revision ID: 9e9bc098186d
Revises:
Create Date: 2026-01-06 15:48:53.954632

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9e9bc098186d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_calendar_sources_id"), table_name="calendar_sources")
    op.drop_table("calendar_sources")
    op.drop_index(op.f("ix_web_services_id"), table_name="web_services")
    op.drop_table("web_services")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "web_services",
        sa.Column("id", sa.VARCHAR(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("url", sa.TEXT(), nullable=False),
        sa.Column("enabled", sa.BOOLEAN(), nullable=False),
        sa.Column("display_order", sa.INTEGER(), nullable=False),
        sa.Column("fullscreen", sa.BOOLEAN(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_web_services_id"), "web_services", ["id"], unique=False)
    op.create_table(
        "calendar_sources",
        sa.Column("id", sa.VARCHAR(), nullable=False),
        sa.Column("type", sa.VARCHAR(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("enabled", sa.BOOLEAN(), nullable=False),
        sa.Column("ical_url", sa.TEXT(), nullable=True),
        sa.Column("api_key", sa.TEXT(), nullable=True),
        sa.Column("color", sa.TEXT(), nullable=True),
        sa.Column("show_time", sa.BOOLEAN(), server_default=sa.text("1"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_calendar_sources_id"), "calendar_sources", ["id"], unique=False)
    # ### end Alembic commands ###
